# PANDAS ASSIGNMENT

1. Create a Pandas series with the following data: {'apples': 3, 'bananas': 2, 'oranges': 1}. Then, add a new item to the series with the key 'pears' and the value 4.

In [16]:
import pandas as pd

In [17]:
fruits=pd.Series({'Apples':3,'Bananas':2, 'Oranges':1})
fruits

Apples     3
Bananas    2
Oranges    1
dtype: int64

In [18]:
fruits['Pears']=4
fruits

Apples     3
Bananas    2
Oranges    1
Pears      4
dtype: int64

2. Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data.

In [28]:
df_per_details=pd.DataFrame({
    'Name':['Amar','Binoy', 'Cini', 'Deepu','Emily', 'Fayaz', 'Greeshma', 'Harish','Indu','Jack'],
    'Age':[22,65,86,74,19,9,12,30,44,93],
    'Gender':['M','F','F','M','F','M','M','F','M','F']
    })
df_per_details

       Name  Age Gender
0      Amar   22      M
1     Binoy   65      F
2      Cini   86      F
3     Deepu   74      M
4     Emily   19      F
5     Fayaz    9      M
6  Greeshma   12      M
7    Harish   30      F
8      Indu   44      M
9      Jack   93      F


3. Add a new column to the data frame created in question 1, called occupation. The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the dataframe.

In [29]:
df_per_details['Occupation']=['Programmer', 'Manager', 'Analyst','Programmer', 'Manager', 'Analyst',
                              'Programmer', 'Manager', 'Analyst','Manager']
df_per_details

       Name  Age Gender  Occupation
0      Amar   22      M  Programmer
1     Binoy   65      F     Manager
2      Cini   86      F     Analyst
3     Deepu   74      M  Programmer
4     Emily   19      F     Manager
5     Fayaz    9      M     Analyst
6  Greeshma   12      M  Programmer
7    Harish   30      F     Manager
8      Indu   44      M     Analyst
9      Jack   93      F     Manager

4. Select the rows of the dataframe where the age is greater than or equal to 30.

In [30]:
df_per_details[df_per_details['Age']>=30]

     Name  Age Gender  Occupation
1   Binoy   65      F     Manager
2    Cini   86      F     Analyst
3   Deepu   74      M  Programmer
7  Harish   30      F     Manager
8    Indu   44      M     Analyst
9    Jack   93      F     Manager

5. Convert this dataframe to a csv file and read that csv file, finally display the contents.

In [32]:
df_per_details.to_csv('Personal_Details.csv')

In [33]:
df1=pd.read_csv('Personal_Details.csv')
df1

   Unnamed: 0      Name  Age Gender  Occupation
0           0      Amar   22      M  Programmer
1           1     Binoy   65      F     Manager
2           2      Cini   86      F     Analyst
3           3     Deepu   74      M  Programmer
4           4     Emily   19      F     Manager
5           5     Fayaz    9      M     Analyst
6           6  Greeshma   12      M  Programmer
7           7    Harish   30      F     Manager
8           8      Indu   44      M     Analyst
9           9      Jack   93      F     Manager